parameters:
    pim_textmaster.mass_edit_action.create_projects.class: Pim\Bundle\TextmasterBundle\MassAction\Operation\CreateProjects

services:
    pim_textmaster.mass_edit_action.create_projects:
        public: false
        class: '%pim_textmaster.mass_edit_action.create_projects.class%'
        arguments:
            - '@security.token_storage'
            - '@translator'
            - 'textmaster_start_projects'
        tags:
            -
                name: pim_enrich.mass_edit_action
                alias: textmaster_start_projects
                datagrid: product-grid
                operation_group: mass-edit
                acl: pim_enrich_product_edit_attributes
                form_type: textmaster.form.create_projects
