services:
    pim_textmaster.tasklet.create_projects:
        class: Pim\Bundle\TextmasterBundle\MassAction\CreateProjectsTasklet
        arguments:
            - '@pim_catalog.repository.locale'
            - '@pim_textmaster.project.builder'
            - '@pim_textmaster.repository.webapi'
            - '@pim_textmaster.saver.project'

    pim_textmaster.tasklet.send_projects:
        class: Pim\Bundle\TextmasterBundle\MassAction\SendProjectsTasklet
        arguments:
            - '@pim_textmaster.repository.webapi'
            - '@oro_config.global'
            - '@translator.default'

    pim_textmaster.tasklet.finalize_projects:
        class: Pim\Bundle\TextmasterBundle\MassAction\FinalizeProjectsTasklet
        arguments:
            - '@pim_textmaster.repository.webapi'
            - '@oro_config.global'
            - '@translator.default'
